/**
 * Shared Type Definitions for Norskprøven Oral Exam
 * Matches the Next.js control-plane schema, Zod validation, and agent worker protocols.
 */

export type CefrLevel = 'B1' | 'B2';

export type CoCandidateMode = 'AI_PEER' | 'HUMAN_LOCAL';

export type ExamSessionStatus = 'ACTIVE' | 'COMPLETED' | 'FAILED';

export type SpeakerRole =
  | 'EXAMINER'
  | 'AI_COCANDIDATE'
  | 'CANDIDATE_1'
  | 'CANDIDATE_2';

/**
 * Exam Topic entity retrieved from the backend catalog
 */
export interface ExamTopic {
  id: string;
  slug: string;
  titleNo: string;
  level: CefrLevel;
  monologuePromptNo: string;
  discussionPromptNo: string;
  followUpQuestionsNo: string[];
  isActive?: boolean;
  createdAt?: string | Date;
}

/**
 * Realtime transcript turn emitted during active exam sessions
 */
export interface TranscriptTurn {
  id?: string;
  speaker: string;
  role: SpeakerRole;
  text: string;
  timestamp: number;
  isFinal?: boolean;
}

/**
 * Criterion score matching HK-dir B1/B2 rubric evaluation
 */
export interface CriterionScore {
  score: number; // 1 - 10
  feedbackNo: string;
  feedbackEn: string;
}

/**
 * Concrete Norwegian correction item generated by rubric evaluator
 */
export interface ConcreteCorrection {
  originalQuote: string;
  correctedNorwegian: string;
  grammarOrVocabRule: string;
}

export type AssessedLevel = 'Under B1' | 'B1' | 'B2' | 'Over B2';

/**
 * Detailed candidate evaluation scorecard for each participant
 */
export interface CandidateEvaluation {
  speakerRole: 'CANDIDATE_1' | 'CANDIDATE_2';
  targetLevel: CefrLevel;
  assessedLevel: AssessedLevel;
  passedTargetLevel: boolean;
  overallSummaryNo: string;
  overallSummaryEn: string;
  criteriaScores: {
    formidlingOgFlyt: CriterionScore;
    uttaleOgForstaelighet: CriterionScore;
    ordforrad: CriterionScore;
    grammatikkOgSetningsstruktur: CriterionScore;
  };
  concreteCorrections: ConcreteCorrection[];
}

/**
 * Complete post-exam evaluation stored in Neon PostgreSQL
 */
export interface ExamEvaluation {
  candidates: CandidateEvaluation[];
  evaluatedAt?: string;
  insufficientData?: boolean;
  notes?: string;
}

/**
 * User quota information from /api/exam/topics or /api/quota
 */
export interface UserQuota {
  remainingAudioSeconds: number;
  totalCostUsd?: string;
}

/**
 * GET /api/exam/topics response payload
 */
export interface GetTopicsResponse {
  topics: ExamTopic[];
  quota: UserQuota;
}

/**
 * POST /api/exam/start request payload
 */
export interface StartExamRequest {
  userId?: string;
  topicId: string;
  level: CefrLevel;
  coCandidateMode: CoCandidateMode;
}

/**
 * POST /api/exam/start response payload
 */
export interface StartExamResponse {
  sessionId: string;
  roomName: string;
  token: string;
  livekitUrl: string;
}

/**
 * Exam phase for Norskprøven oral test structure
 */
export type ExamStage = 'DEL_1' | 'DEL_2' | 'DEL_3';

/**
 * React Navigation Stack parameter list
 */
export type RootStackParamList = {
  ExamSetup: undefined;
  ExamRoom: {
    sessionId: string;
    roomName: string;
    token: string;
    livekitUrl: string;
    level: CefrLevel;
    coCandidateMode: CoCandidateMode;
    topicTitle: string;
  };
  ExamResults: {
    sessionId: string;
  };
};

